# --- !Ups

CREATE TABLE "CATEGORY"
(
    "CAT_ID"          INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "CAT_CODE"        VARCHAR,
    "CAT_NAME"        VARCHAR,
    "CAT_REMOVE_DATE" DATE,
    "CAT_CREATE_DATE" DATE,
    "CAT_MODIFY_DATE" DATE,
    CONSTRAINT CAT_CODE_U UNIQUE (CAT_CODE, CAT_REMOVE_DATE)
);

CREATE TABLE "PRODUCTS"
(
    "PRD_ID"          INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "PRD_NAME"        VARCHAR,
    "PRD_CODE"        VARCHAR,
    "PRD_DESCRIPTION" TEXT,
    "PRD_REMOVE_DATE" DATE,
    "PRD_MODIFY_DATE" DATE,
    "PRD_CREATE_DATE" DATE,
    "PRD_VALUE"       DOUBLE,
    "PRD_CAT_ID"      INTEGER,
    FOREIGN KEY (PRD_CAT_ID) REFERENCES CATEGORY (CAT_ID),
    CONSTRAINT PRD_CODE_U UNIQUE (PRD_CODE, PRD_REMOVE_DATE)
);

CREATE TABLE "CARDS"
(
    "CRD_ID"          INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "CRD_NUM"         VARCHAR,
    "CRD_STATUS"      VARCHAR,
    "CRD_POINTS"      INTEGER DEFAULT 0,
    "CRD_MODIFY_DATE" DATE,
    "CRD_CREATE_DATE" DATE,
    "CRD_CTM_ID"      INTEGER,
    FOREIGN KEY (CRD_CTM_ID) REFERENCES CUSTOMERS (CTM_ID),
    CONSTRAINT CRD_NUM_U UNIQUE (CRD_NUM)
);

CREATE TABLE "COUPONS"
(
    "CPN_ID"             INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "CPN_NUM"            VARCHAR,
    "CPN_STATUS"         VARCHAR,
    "CPN_DISCOUNT_VALUE" DOUBLE DEFAULT 0,
    "CPN_MODIFY_DATE"    DATE,
    "CPN_CREATE_DATE"    DATE,
    "CPN_REMOVE_DATE"    DATE,
    "CPN_CTM_ID"         INTEGER,
    FOREIGN KEY (CPN_CTM_ID) REFERENCES CUSTOMERS (CTM_ID),
    CONSTRAINT CPN_NUM_U UNIQUE (CPN_NUM)
);

CREATE TABLE "CUSTOMERS"
(
    "CTM_ID"           INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "CTM_NAME"         VARCHAR,
    "CTM_SURNAME"      VARCHAR,
    "CTM_STATUS"       VARCHAR,
    "CTM_MODIFY_DATE"  DATE,
    "CTM_CREATE_DATE"  DATE,
    "CTM_CLOSURE_DATE" DATE,
    "CTM_PASSWORD"     VARCHAR,
    "CTM_LOGIN"        VARCHAR,
    "CTM_BIRTH_DATE"   DATE,
    CONSTRAINT CTM_LOGIN_U UNIQUE (CTM_LOGIN, CTM_CLOSURE_DATE)
);

CREATE TABLE "LOCATIONS"
(
    "LCN_ID"          INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "LCN_CODE"        VARCHAR,
    "LCN_TYPE"        VARCHAR,
    "LCN_MODIFY_DATE" DATE,
    "LCN_CREATE_DATE" DATE,
    "LCN_REMOVE_DATE" DATE,
    "LCN_DESCRIPTION" TEXT,
    CONSTRAINT LCN_CODE_U UNIQUE (LCN_CODE, LCN_REMOVE_DATE)
);

CREATE TABLE "OFFERS"
(
    "OFR_ID"          INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "OFR_NAME"        VARCHAR,
    "OFR_DESCRIPTION" TEXT,
    "OFR_CODE"        VARCHAR,
    "OFR_MODIFY_DATE" DATE,
    "OFR_CREATE_DATE" DATE,
    "OFR_REMOVE_DATE" DATE,
    "OFR_START_DATE"  DATE,
    "OFR_END_DATE"    DATE,
    CONSTRAINT OFR_CODE_U UNIQUE (OFR_CODE, OFR_REMOVE_DATE)
);

CREATE TABLE "ORDERS_PRODUCTS"
(
    "OP_ID"           INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "OP_CREATE_DATE"  DATE,
    "OP_REMOVE_DATE"  DATE,
    "OP_PRD_ID"       INTEGER,
    "OP_ORD_ID"       INTEGER,
    "OP_PRD_QUANTITY" INTEGER,
    FOREIGN KEY (OP_PRD_ID) REFERENCES PRODUCTS (PRD_ID),
    FOREIGN KEY (OP_ORD_ID) REFERENCES ORDERS (ORD_ID),
    CONSTRAINT OP_ORDER_PRD_U UNIQUE (OP_PRD_ID, OP_ORD_ID)
);

CREATE TABLE "ORDERS"
(
    "ORD_ID"          INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "ORD_MODIFY_DATE" DATE,
    "ORD_CREATE_DATE" DATE,
    "ORD_REMOVE_DATE" DATE,
    "ORD_DISCOUNT"    DOUBLE DEFAULT 0,
    "ORD_CTM_ID"      INTEGER,
    FOREIGN KEY (ORD_CTM_ID) REFERENCES CUSTOMERS (CTM_ID)
);

CREATE TABLE "TRANSACTIONS"
(
    "TRA_ID"          INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "TRA_MODIFY_DATE" DATE,
    "TRA_CREATE_DATE" DATE,
    "TRA_STATUS"      VARCHAR,
    "TRA_VALUE"       DOUBLE,
    "TRA_ORD_ID"      INTEGER,
    "TRA_COMMENT"     TEXT,
    "TRA_CTM_ID"      INTEGER,
    "TRA_LCN_ID"      INTEGER,
    "TRA_TYPE"        VARCHAR,
    FOREIGN KEY (TRA_ORD_ID) REFERENCES ORDERS (ORD_ID),
    FOREIGN KEY (TRA_CTM_ID) REFERENCES CUSTOMERS (CTM_ID),
    FOREIGN KEY (TRA_LCN_ID) REFERENCES LOCATIONS (LCN_ID)
);

CREATE TABLE "SHOPPING_CART"
(
    "SHC_ID"          INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "SHC_MODIFY_DATE" DATE,
    "SHC_CREATE_DATE" DATE,
    "SHC_REMOVE_DATE" DATE,
    "SHC_VALUE"       DOUBLE DEFAULT 0,
    "SHC_CTM_ID"      INTEGER,
    "SHC_ORD_ID"      INTEGER,
    FOREIGN KEY (SHC_CTM_ID) REFERENCES CUSTOMERS (CTM_ID),
    FOREIGN KEY (SHC_ORD_ID) REFERENCES ORDERS (ORD_ID)
);

CREATE TABLE "SHOPPING_CART_PRODUCTS"
(
    "SP_ID"           INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "SP_PRD_ID"       INTEGER,
    "SP_SHC_ID"       INTEGER,
    "SP_PRD_QUANTITY" INTEGER,
    "SP_VALUE"        DOUBLE,
    FOREIGN KEY (SP_PRD_ID) REFERENCES PRODUCTS (PRD_ID),
    FOREIGN KEY (SP_SHC_ID) REFERENCES SHOPPING_CART (SHC_ID) ON DELETE CASCADE,
    CONSTRAINT SP_PRD_U UNIQUE (SP_PRD_ID, SP_SHC_ID)
);

# --- !Downs

DROP TABLE "PRODUCTS";
DROP TABLE "CATEGORY";
DROP TABLE "CARDS";
DROP TABLE "COUPONS";
DROP TABLE "CUSTOMERS";
DROP TABLE "LOCATIONS";
DROP TABLE "OFFERS";
DROP TABLE "ORDERS_PRODUCTS";
DROP TABLE "ORDERS";
DROP TABLE "TRANSACTIONS";
DROP TABLE "SHOPPING_CART";
DROP TABLE "SHOPPING_CART_PRODUCTS";